// ──────────────────────────────────────────────────────────────────
// UI component seeds — the canonical definitions of the reusable UI
// components (text input, select, date picker, …) that field elements
// reference via `uiComponentId`.
//
// Single source of truth for:
//   - the backend `ui_components` table (back's seed re-exports this)
//   - the frontend's CUID → componentType mapping (UI_TYPE_MAP is
//     derived from UI_COMPONENTS_SEED)
// ──────────────────────────────────────────────────────────────────

import type { UiComponentSeed } from "./types";

/** CUID namespace for UI components (mirrors the backend registry). */
export const UI_COMPONENT_CUIDS = {
	textInput: "ehyogseqi0finqr3nxvrloz9",
	textarea: "ntei44cohh13u9ucn39vcyk6",
	numberInput: "yre76a811cgd0gah7slikx7n",
	emailInput: "ljim0jdtwehy2u4bmizcl5l1",
	passwordInput: "tocuq2ddmh63873sozdtsxzv",
	select: "ulrl8i5mvw8xdtx1mvy8nweh",
	multiselect: "n1a36mr1qezahbe933cvyfob",
	radio: "xeygn35o9r4wwqffgkfnrk7v",
	checkbox: "ug6fakpjm1i4lmuovsnt0avo",
	switch: "doz363xcy9jvlqsfrhznhtzq",
	datePicker: "o41skpeesjg0mkkfibxx7byk",
	dateTimePicker: "esnuxby399h4x9vef1a7pvfe",
	timePicker: "nod2qtt86s18ikgk3g2facuz",
	fileUpload: "sp1lvjf74s8o2qb95zrb4pbl",
	imageUpload: "h2mtp5nuwcd0wze93wobr8u6",
	richtextEditor: "s07ljezsn03enysedxu5g9r7",
	jsonEditor: "iohrvkm1dpkg2yg5d6wuv7z8",
	referenceSelect: "drjllunrc3zl0bt1dztjcmp6",
	autocomplete: "e18e47v29py88decf28m2b8v",
} as const;

export const UI_COMPONENTS_SEED: UiComponentSeed[] = [
	{
		id: UI_COMPONENT_CUIDS.textInput,
		name: "text-input",
		displayName: "Text Input",
		description: "Standard single-line text input",
		componentType: "text",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			maxLength: { type: "number", label: "Max Length" },
			minLength: { type: "number", label: "Min Length" },
			pattern: { type: "string", label: "Regex Pattern" },
			prefixIcon: { type: "string", label: "Prefix Icon" },
			suffixIcon: { type: "string", label: "Suffix Icon" },
			autoComplete: { type: "string", label: "Auto Complete" },
		},
		compatibleFieldTypes: ["text"],
		displayOrder: 1,
		category: "basic",
		tags: ["text", "single-line", "input"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.textarea,
		name: "textarea",
		displayName: "Text Area",
		description: "Multi-line text input",
		componentType: "textarea",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			maxLength: { type: "number", label: "Max Length" },
			rows: { type: "number", label: "Visible Rows" },
		},
		compatibleFieldTypes: ["textarea"],
		displayOrder: 2,
		category: "basic",
		tags: ["text", "multi-line", "textarea"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.numberInput,
		name: "number-input",
		displayName: "Number Input",
		description: "Numeric input with increment/decrement",
		componentType: "number",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			min: { type: "number", label: "Minimum Value" },
			max: { type: "number", label: "Maximum Value" },
			step: { type: "number", label: "Step Size" },
			prefixIcon: { type: "string", label: "Prefix Icon" },
			suffixIcon: { type: "string", label: "Suffix Icon" },
		},
		compatibleFieldTypes: ["number"],
		displayOrder: 3,
		category: "basic",
		tags: ["number", "numeric", "input"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.emailInput,
		name: "email-input",
		displayName: "Email Input",
		description: "Email address input with validation",
		componentType: "email",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			autoComplete: { type: "string", label: "Auto Complete" },
		},
		compatibleFieldTypes: ["email"],
		displayOrder: 4,
		category: "basic",
		tags: ["email", "input"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.passwordInput,
		name: "password-input",
		displayName: "Password Input",
		description: "Password input with masking",
		componentType: "password",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			autoComplete: { type: "string", label: "Auto Complete" },
		},
		compatibleFieldTypes: ["password"],
		displayOrder: 5,
		category: "basic",
		tags: ["password", "input", "secure"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.select,
		name: "select",
		displayName: "Select Dropdown",
		description: "Single-select dropdown from predefined options",
		componentType: "select",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
		},
		compatibleFieldTypes: ["select"],
		displayOrder: 6,
		category: "selection",
		tags: ["select", "dropdown", "single"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.multiselect,
		name: "multiselect",
		displayName: "Multi-Select",
		description: "Multi-select dropdown with chips/tags",
		componentType: "multiselect",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
		},
		compatibleFieldTypes: ["multiselect"],
		displayOrder: 7,
		category: "selection",
		tags: ["select", "multi", "chips"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.radio,
		name: "radio-group",
		displayName: "Radio Group",
		description: "Radio button group for mutually exclusive selection",
		componentType: "radio",
		configProps: {},
		compatibleFieldTypes: ["radio"],
		displayOrder: 8,
		category: "selection",
		tags: ["radio", "selection", "single"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.checkbox,
		name: "checkbox",
		displayName: "Checkbox",
		description: "Single boolean checkbox toggle",
		componentType: "checkbox",
		configProps: {},
		compatibleFieldTypes: ["checkbox"],
		displayOrder: 9,
		category: "selection",
		tags: ["checkbox", "toggle", "boolean"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.switch,
		name: "toggle-switch",
		displayName: "Toggle Switch",
		description: "On/off toggle switch for boolean values",
		componentType: "switch",
		configProps: {},
		compatibleFieldTypes: ["switch"],
		displayOrder: 10,
		category: "selection",
		tags: ["switch", "toggle", "boolean"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.datePicker,
		name: "date-picker",
		displayName: "Date Picker",
		description: "Calendar date selection",
		componentType: "date",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			min: { type: "string", label: "Min Date (ISO)" },
			max: { type: "string", label: "Max Date (ISO)" },
		},
		compatibleFieldTypes: ["date"],
		displayOrder: 11,
		category: "date-time",
		tags: ["date", "picker", "calendar"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.dateTimePicker,
		name: "datetime-picker",
		displayName: "Date-Time Picker",
		description: "Combined date and time selection",
		componentType: "datetime",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			min: { type: "string", label: "Min Date-Time (ISO)" },
			max: { type: "string", label: "Max Date-Time (ISO)" },
		},
		compatibleFieldTypes: ["datetime"],
		displayOrder: 12,
		category: "date-time",
		tags: ["datetime", "picker", "calendar"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.timePicker,
		name: "time-picker",
		displayName: "Time Picker",
		description: "Time selection picker",
		componentType: "time",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			min: { type: "string", label: "Min Time (HH:mm)" },
			max: { type: "string", label: "Max Time (HH:mm)" },
		},
		compatibleFieldTypes: ["time"],
		displayOrder: 13,
		category: "date-time",
		tags: ["time", "picker"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.fileUpload,
		name: "file-upload",
		displayName: "File Upload",
		description: "File upload with drag-and-drop support",
		componentType: "file",
		configProps: {
			accept: { type: "string", label: "Accepted MIME Types" },
			multiple: { type: "boolean", label: "Allow Multiple" },
			maxSize: { type: "number", label: "Max File Size (bytes)" },
		},
		compatibleFieldTypes: ["file"],
		displayOrder: 14,
		category: "media",
		tags: ["file", "upload", "drag-drop"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.imageUpload,
		name: "image-upload",
		displayName: "Image Upload",
		description: "Image upload with preview and cropping",
		componentType: "image",
		configProps: {
			accept: { type: "string", label: "Accepted Image Types" },
			multiple: { type: "boolean", label: "Allow Multiple" },
			maxSize: { type: "number", label: "Max Image Size (bytes)" },
		},
		compatibleFieldTypes: ["image"],
		displayOrder: 15,
		category: "media",
		tags: ["image", "upload", "preview"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.richtextEditor,
		name: "richtext-editor",
		displayName: "Rich Text Editor",
		description: "WYSIWYG rich text editing with formatting toolbar",
		componentType: "richtext",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			maxLength: { type: "number", label: "Max Length" },
		},
		compatibleFieldTypes: ["richtext"],
		displayOrder: 16,
		category: "advanced",
		tags: ["richtext", "editor", "wysiwyg"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.jsonEditor,
		name: "json-editor",
		displayName: "JSON Editor",
		description: "JSON editor with syntax highlighting and validation",
		componentType: "json",
		configProps: {},
		compatibleFieldTypes: ["json"],
		displayOrder: 17,
		category: "advanced",
		tags: ["json", "editor", "code"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.referenceSelect,
		name: "reference-select",
		displayName: "Reference Select",
		description: "Searchable selector for related records",
		componentType: "reference",
		configProps: {
			displayField: { type: "string", label: "Display Field" },
			endpoint: { type: "string", label: "API Endpoint" },
		},
		compatibleFieldTypes: ["reference"],
		displayOrder: 18,
		category: "advanced",
		tags: ["reference", "relation", "selector"],
		isSystem: true,
		isActive: true,
	},
	{
		id: UI_COMPONENT_CUIDS.autocomplete,
		name: "autocomplete",
		displayName: "Autocomplete",
		description: "Searchable autocomplete with remote data source",
		componentType: "autocomplete",
		configProps: {
			placeholder: { type: "string", label: "Placeholder" },
			debounce: { type: "number", label: "Debounce (ms)" },
			minChars: { type: "number", label: "Min Characters" },
		},
		compatibleFieldTypes: ["autocomplete"],
		displayOrder: 19,
		category: "advanced",
		tags: ["autocomplete", "search", "dropdown"],
		isSystem: true,
		isActive: true,
	},
];
